name: Deploy to Cloud Run
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.FULL_PERMISSIONS_SERVICE_ACCOUNT_KEY }}'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    - name: 'Deploy to Cloud Run'
      run: |
        gcloud run deploy sim-consciousness-fixed \
          --source . \
          --region us-central1 \
          --allow-unauthenticated \
          --port 8080 \
          --memory 1Gi \
          --cpu 1 \
          --set-env-vars DATABASE_URL="${{ secrets.DATABASE_URL }}"
